routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('weather', 'App\Http\Controllers\WeatherController');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/WeatherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Cache;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class WeatherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('weather');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $params = $this->validate($request, ['country'=>'required|max:2','city'=>'required']);
        $key = strtolower($params['city']).'-'.strtolower($params['city']);
        $avg = Cache::get($key);
        if (  $avg == null ){
            $avg = $this->getWeatherTemperature($params['country'],$params['city'], $key);
        }
        return redirect()->back()->with(['avg'=>$avg]);
    }


    private function getWeatherTemperature( $country, $city , $key ){
        $response = json_decode(file_get_contents(
            "http://api.weatherbit.io/v2.0/forecast/daily?key=".env('WEATHER_KEY')."&days=10&city=$city&country=$country"));
        try{
            $avg = 0;
            foreach ( $response->data as $data ){
                $avg += $data->temp;
            }
            $avg /= 10;
        }catch ( \Exception $e ){
            $avg = 'N/A';
        }
        Cache::put($key, $avg , now()->addHours(2));
        return $avg;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/weather.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Weather Task</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <h2>Weather AVG</h2>
    <form action="{{route('weather.store')}}" method="POST">
        @csrf
        @method('POST')
        <div class="form-group">
            <label for="country">Country Code (2 characters):</label>
            <input type="text" class="form-control" id="country" placeholder="Enter country" name="country" required>
        </div>
        <div class="form-group">
            <label for="city">City Name:</label>
            <input type="text" class="form-control" id="city" placeholder="Enter city" name="city" required>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
        @if(\Illuminate\Support\Facades\Session::has('avg'))
            <div class="form-group">
                <label for="city">The Average Temperature for the next 10 days is :</label>
                <input type="text" class="form-control"  value="{{\Illuminate\Support\Facades\Session::get('avg')}}" readonly >
            </div>
        @endisset
    </form>
</div>

</body>
</html>